= REST API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

ifndef::snippets[]
:snippets: ./build/generated-snippets
:roots: ./build/generated-snippets
endif::[]

== Verb
|===
| Verb | Usage
| `GET`
| Used to retrieve a resource
| `POST`
| Used to create a new resource
| `PATCH`
| Used to update an existing resource, including partial updates
| `DELETE`
| Used to delete an existing resource
|===

== Status
|===
| Status code | Usage
| `200 OK`
| The request completed successfully
| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header
| `204 No Content`
| An update to an existing resource has been applied successfully
| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information
| `404 Not Found`
| The requested resource did not exist
|===

== Host
|===
|환경|Host
|LOCAL|http://localhost:8080
|===

== APIs
URL은 `/api/`로 시작한다.

== Sign Up API

=== User 회원가입 성공 [POST]
operation::signup/user/success[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== User 회원가입 실패 [POST]
operation::signup/user/fail[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== MANAGER 회원가입 성공 [POST]
operation::signup/manager/success[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== MANAGER 회원가입 실패 [POST]
operation::signup/manager/fail[snippets='curl-request,http-request,http-response,response-body,response-fields']

== Login Api

=== USER 로그인 성공 [POST]
operation::login/user/success[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== USER 로그인 실패 [POST]
operation::login/user/fail[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== MANAGER 로그인 성공 [POST]
operation::login/manager/success[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== MANAGER 로그인 실패 [POST]
operation::login/manager/fail[snippets='curl-request,http-request,http-response,response-body,response-fields']

== Logout Api

=== User 로그아웃 [POST]
operation::logout[snippets='curl-request,http-request,http-response,response-body,response-fields']


== 토큰 Api

=== 토큰 재발급 [POST]
operation::reissue[snippets='curl-request,http-request,http-response,response-body,response-fields']

== User Api

=== USER 조회 [GET]
operation::users/me[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== USER 업데이트 [PATCH]
operation::users/update[snippets='curl-request,http-request,http-response,response-body,response-fields']

== Shop Api

=== SHOP 전체 조회 [GET]
operation::shops/findAll[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== SHOP 조회 [GET]
operation::shops/find[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== SHOP 추가 [POST]
operation::shops/add[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== SHOP 업데이트 [POST]
operation::shops/update[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== SHOP 삭제 [DELETE]
operation::shops/delete[snippets='curl-request,http-request,http-response,response-body,response-fields']

== Product Api

=== PRODUCT 전체 조회 [GET]
operation::products/findAll[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 조회 [GET]
operation::products/find[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 추가 [POST]
operation::products/add[snippets='pat curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 업데이트 [POST]
operation::products/update[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 우선순위 업데이트 [PATCH]
operation::products/updatePriority[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 삭제 [DELETE]
operation::products/delete[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 추천 조회 [GET]
operation::products/recommend[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT 카테고리 조회 [GET]
operation::products/category[snippets='curl-request,http-request,http-response,response-body,response-fields']

=== PRODUCT Shop 별 우선순위 조회 [GET]
operation::products/shop[snippets='curl-request,http-request,http-response,response-body,response-fields']
