spring:
  jwt:
    secret: ${{secrets.JWT_KEY}}
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

cloud:
  aws:
    s3:
      bucket: toogoodtogobucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
