spring:
  jwt:
    secret: jwt
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:mem:toogoodtogo
  redis:
    host: localhost
    port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

cloud:
  minio:
    access-key: admin
    secret-key: password
    endpoint: http://127.0.0.1:9000
  aws:
    s3:
      bucket: toogoodtogobucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudFront:
      distributionDomain: https://diefqsnmvol80.cloudfront.net