spring:
  profiles:
    include: jwt

  messages:
    basename: i18n/exception
    encoding: UTF-8
<<<<<<< HEAD

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
=======
    
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
>>>>>>> 330b3d096489230e1e42f4462d500df7d4d16a66
