spring:
  jwt:
    secret: ${JWT_KEY}
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${REDIS_HOST}
    port: 6379

cloud:
  aws:
    credentials:
      instanceProfile: true
    s3:
      bucket: toogoodtogobucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudFront:
      distributionDomain: https://diefqsnmvol80.cloudfront.net

logging:
  level:
    root: error