export const shopData = [
	{
		shopId: 0,
		shopFoodImg: "image/food2.jpg",
		shopName: "전주비빔밥",
		shopFoodName: "전통 전주비빔밥",
		shopFoodSale: 10,
		shopFoodCost: 9000,
		shopBeforeCost: 10000,
	},
	{
		shopId: 1,
		shopFoodImg: "image/food3.jpg",
		shopName: "전통 부대찌개 맛집",
		shopFoodName: "맛있는 부대찌개",
		shopFoodSale: 5,
		shopFoodCost: 9500,
		shopBeforeCost: 10000,
	},
	{
		shopId: 2,
		shopFoodImg: "image/food2.jpg",
		shopName: "전주비빔밥",
		shopFoodName: "전통 전주비빔밥",
		shopFoodSale: 10,
		shopFoodCost: 9000,
		shopBeforeCost: 10000,
	},
	{
		shopId: 3,
		shopFoodImg: "image/food3.jpg",
		shopName: "전통 부대찌개 맛집",
		shopFoodName: "맛있는 부대찌개",
		shopFoodSale: 5,
		shopFoodCost: 9500,
		shopBeforeCost: 10000,
	},
	{
		shopId: 4,
		shopFoodImg: "image/food2.jpg",
		shopName: "전주비빔밥",
		shopFoodName: "전통 전주비빔밥",
		shopFoodSale: 10,
		shopFoodCost: 9000,
		shopBeforeCost: 10000,
	},
	{
		shopId: 5,
		shopFoodImg: "image/food3.jpg",
		shopName: "전통 부대찌개 맛집",
		shopFoodName: "맛있는 부대찌개",
		shopFoodSale: 5,
		shopFoodCost: 9500,
		shopBeforeCost: 10000,
	},
	{
		shopId: 6,
		shopFoodImg: "image/food2.jpg",
		shopName: "전주비빔밥",
		shopFoodName: "전통 전주비빔밥",
		shopFoodSale: 10,
		shopFoodCost: 9000,
		shopBeforeCost: 10000,
	},
	{
		shopId: 7,
		shopFoodImg: "image/food3.jpg",
		shopName: "전통 부대찌개 맛집",
		shopFoodName: "맛있는 부대찌개",
		shopFoodSale: 5,
		shopFoodCost: 9500,
		shopBeforeCost: 10000,
	},
	{
		shopId: 8,
		shopFoodImg: "image/food2.jpg",
		shopName: "전주비빔밥",
		shopFoodName: "전통 전주비빔밥",
		shopFoodSale: 10,
		shopFoodCost: 9000,
		shopBeforeCost: 10000,
	},
	{
		shopId: 9,
		shopFoodImg: "image/food3.jpg",
		shopName: "전통 부대찌개 맛집",
		shopFoodName: "맛있는 부대찌개",
		shopFoodSale: 5,
		shopFoodCost: 9500,
		shopBeforeCost: 10000,
	},
];
