# workflow의 이름
name: Backend_CD

# workflow가 언제 실행될건지
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/Backend_CD.yml
      - 'Back/**'
jobs:
  build-and-push:
    # Github action 스크립트가 작동될 OS 환경
    runs-on: ubuntu-latest
    env:
      working-directory: ./Back

    steps:
    - name: Checkout
      uses: actions/checkout@v2 # 프로젝트 코드로 checkout
    
    # gradle 빌드 (build+test)
    - name: Build with Gradle
      working-directory: ./Back
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-latest # runner 설정에서 읽어들일거
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./Back
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/kanghayeonn/too-good-to-go:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Force new deploy ECS service
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ${{ env.working-directory }}
      run: aws ecs update-service --cluster main --service api-server --force-new-deployment
    
    # Slack 알림
    - name: CD notification to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Backend CD
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BACKEND_WEBHOOK_URL }}
