# workflow의 이름
name: Backend_CI
# workflow가 언제 실행될건지
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/Backend_CI.yml
      - 'Back/**'
jobs:
  backend:
    name: CI with Gradle
    # Github action 스크립트가 작동될 OS 환경
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: tgtg
          MYSQL_PASSWORD: 1234
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toogoodtogo
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      working-directory: ./Back
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # 프로젝트 코드로 checkout
    - name: Set up JDK 11
      uses: actions/setup-java@v1 # Github action이 실행될 OS에 Java 설치
      with:
        java-version: 11 # JDK 11 버전 사용
    # gradle 빌드 (build+test)
    - name: Build with Gradle
      working-directory: ./Back
      run: |
        chmod +x ./gradlew
        ./gradlew build
    # 결과 저장
    - name: If failure then upload test reports
      if: failure() # 테스트나 빌드가 실패시 실행
      run: |
        TARBALL_BASENAME="r6-stats-report"
        TARBALL="$TARBALL_BASENAME.tar"
        echo 'Collecting the test report'
        find . -path '*/build/reports/tests' -type d \
          -exec tar rf "$TARBALL" \
            --xform="s:./:$TARBALL_BASENAME/:" \
            --xform='s:/build/reports/tests::' \
            {} ';'
        echo 'Compressing the test reports .. '
        gzip "$TARBALL"
        echo 'Uploading the test reports .. '
        curl -F "file=@$TARBALL.gz" 'https://file.io/'
        echo
        echo 'Download the test reports from the URL above.'
    # Slack 알림
    - name: CI notification to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Backend CI
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BACKEND_WEBHOOK_URL }}
