# workflow의 이름
name: CI

# workflow가 언제 실행될건지
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Github action 스크립트가 작동될 OS 환경
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2 # 프로젝트 코드로 checkout
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1 # Github action이 실행될 OS에 Java 설치
      with:
        java-version: 11 # JDK 11 버전 사용
        
    # gradlew 권한 부여
    - name: Grant execute premission to gradlew
      run: chmod +x gradlew # gradlew를 사용하기 위한 실행권한 획득
      
    # gradle 빌드
    - name: Build with Gradle
      run: ./gradlew build
